// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjBr8vly8wSpIM0hLVSfP6koWCDyXGBc0',
    appId: '1:914241253175:web:6166e04cbd2b846aa1f4b2',
    messagingSenderId: '914241253175',
    projectId: 'supertache-36df7',
    authDomain: 'supertache-36df7.firebaseapp.com',
    storageBucket: 'supertache-36df7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZvedJvqMwbVImuqRl3Df5vQXitd3tLRY',
    appId: '1:914241253175:android:2f44fa2f123dd34ba1f4b2',
    messagingSenderId: '914241253175',
    projectId: 'supertache-36df7',
    storageBucket: 'supertache-36df7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-7CID0l11_m6PnKjavR3c8-8tgm9ixd0',
    appId: '1:914241253175:ios:985b37a00901a5e0a1f4b2',
    messagingSenderId: '914241253175',
    projectId: 'supertache-36df7',
    storageBucket: 'supertache-36df7.firebasestorage.app',
    iosBundleId: 'com.supertache.supertache',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-7CID0l11_m6PnKjavR3c8-8tgm9ixd0',
    appId: '1:914241253175:ios:c928eb787df69a5ba1f4b2',
    messagingSenderId: '914241253175',
    projectId: 'supertache-36df7',
    storageBucket: 'supertache-36df7.firebasestorage.app',
    iosBundleId: 'org.deguet.supertache',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjBr8vly8wSpIM0hLVSfP6koWCDyXGBc0',
    appId: '1:914241253175:web:1fb02f8e513cb788a1f4b2',
    messagingSenderId: '914241253175',
    projectId: 'supertache-36df7',
    authDomain: 'supertache-36df7.firebaseapp.com',
    storageBucket: 'supertache-36df7.firebasestorage.app',
  );
}
